[book]
authors = ["msaug"]
language = "en"
multilingual = false
src = "src"
title = "Starknet by Example"

[build]
# Eventual translations
# extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[output.html]
git-repository-url = "https://github.com/NethermindEth/StarknetByExample/"
edit-url-template = "https://github.com/NethermindEth/StarknetByExample/edit/main/{path}"
playground.runnable = false