name: Verify Cairo programs compilation

description: Verify if all Cairo programs extracted from markdown can be compiled.

runs:
  using: composite
  steps:
    - name: Install scarb
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | bash -s -- -v 0.4.0

    - name: Copy Cairo program verifier script
      shell: bash
      run: |
        mkdir -p book/listings && cp scripts/cairo_programs_verifier.sh book/listings && cp listings book/listings

    - name: Run build script
      run: |
        chmod +x scripts/cairo_programs_verifier.sh
        ./scripts/cairo_programs_verifier.sh
