name: Verify Cairo programs compilation

description: Verify if all Cairo programs extracted from markdown can be compiled.

runs:
  using: composite
  steps:
    - name: Install scarb
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | bash -s -- -v 0.5.1

    - name: Run build script
      shell: bash
      run: |
        chmod +x scripts/cairo_programs_verifier.sh
        ./scripts/cairo_programs_verifier.sh
